# Generated by Django 3.1.7 on 2021-04-02 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.TextField(unique=True)),
                ('paciente_sexo', models.TextField()),
                ('numero_acesso', models.TextField()),
                ('data_estudo', models.TextField()),
                ('espacamento_slice', models.TextField()),
            ],
            options={
                'db_table': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(choices=[('pneumonia', 'Pneumonia'), ('tuberculose', 'Tuberculose'), ('normal', 'Normal')], max_length=11)),
                ('grau_de_severidade', models.CharField(choices=[('grave', 'Grave'), ('moderado', 'Moderado'), ('leve', 'Leve'), ('ausente', 'Ausente')], max_length=11)),
                ('nivel_de_normalidade', models.CharField(choices=[('tipico', 'Típico'), ('atipico', 'Atípico')], max_length=10)),
                ('paciente_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', to_field='paciente_id')),
            ],
            options={
                'db_table': 'Diagnóstico',
            },
        ),
    ]
