# Generated by Django 3.1.7 on 2021-04-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
