# Generated by Django 3.1.7 on 2021-04-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20210403_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.CharField(blank=True, choices=[('pneumonia', 'Pneumonia'), ('tuberculose', 'Tuberculose'), ('normal', 'Normal')], max_length=11),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grau_de_severidade',
            field=models.CharField(blank=True, choices=[('grave', 'Grave'), ('moderado', 'Moderado'), ('leve', 'Leve'), ('ausente', 'Ausente')], max_length=11),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nivel_de_normalidade',
            field=models.CharField(blank=True, choices=[('tipico', 'Típico'), ('atipico', 'Atípico')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Diagnostico',
        ),
    ]
