# Generated by Django 3.1.7 on 2021-04-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20210403_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paciente_id',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
